### ISSUE TITLE
Licence terms not followed

### ISSUE THREAD

**Issue by ProditorMagnus** [xUndisputed/titanmusic#1]
"Modifications (including forks) of the code to fit personal needs are allowed only for personal use and should refer back to the original source."

**Comment by Trigstur** [comment]
If this issue still applies please mail me your license and a copyright complaint

Note: I have nothing to do with stealing your bot/script or causing any other copyright-related damage

I just have access to this repository and know that this will not be handled professionally by anyone else here.

**Comment by Trigstur** [comment]
trigstur@gmail.com

**Comment by ProditorMagnus** [comment]
I am not involved in it, but this repo is obvious copy of https://github.com/basicBot/source.
